### ISSUE TITLE
STA9750 fatima8808 MiniProject #01

### ISSUE THREAD

**Issue by fatima8808** [fatima8808/STA9750-2024-FALL#2]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #01 - check it out!

https://fatima8808.github.io/STA9750-2024-FALL/mp01.html

**Comment by michaelweylandt** [comment]
Thanks @fatima8808 !

Peer Feedback:

- @ElissaLeung
- @greazyz
- @Cdiallo77
- @mt1536

It is now time for the peer feedback round for Mini-Project #01. Please
review @fatima8808's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric,
please grade their submission out of a total of 50 points.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @fatima8808, but you are of course
welcome to initiate a discussion.

@fatima8808: please engage fully with your peers. They are here to help you!

Submission URL should be: https://fatima8808.github.io/STA9750-2024-FALL/mp01.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by mt1536** [comment]
Hi @fatima8808  !

Thank you for submitting:

-Written communication: 10/10. Very organized and well written including context and appropriate details 

-Project Skeleton: 10/10. Tasks successfully completed

-Formatting & Display : 10/10: Very good formatting with proper use of titles and introduction of code

-Code Quality: 10/10. Code seems easy to read, and able to execute. Basically flawless

-Data Preparation: 10/10

Total: 50/50

Regards,
mt1536

**Comment by ElissaLeung** [comment]
Hi @fatima8808! I enjoyed reading through your mini project #01 submission.

Here's my feedback:

**Written Communication:** 10/10
I liked that you gave an in-depth introduction to each topic you explored and how you thoroughly explained each metric you explored.

**Project Skeleton:** 10/10
Great job finishing all the tasks!

**Formatting & Display:** 10/10
Only suggestion I have is to also display the USAGE_AND_FINANCIALS data table for the second part of the project at the end using the DT::datatable(). Also, whenever you display multiple records of information, it might be better to use the DT::datatable() display instead of just the tibble. These are just suggestions and based what your personal preference is!

**Code Quality:** 10/10
Your code looks clean and runs well!

**Data Preparation:** 10/10

**Total:** 50/50

Once again, I loved reading through your project submission!

Elissa

**Comment by Cdiallo77** [comment]
Hell @fatima8808 

This is probably one of the best mini project 1 I read. 

1. For the written communication I give you 10. I like the picture at the beginning and all the links you included. 
2. Project Skeleton is also 10 as you successfully completed all the tasks.
3. Formatting & Display 10 proper formatting with titles and formatting.
4. Code Quality 10, easy to read.
5. Data Preparation 10

In Total: 50/50, this is great help for me. I'll be reviewing how you did your work to improve my skills. 

Great Job, 
Cdiallo77.

**Comment by charles-ramirez** [comment]
Hi  @greazyz,

This is just a reminder that your peer review is due today at 11:45 pm.

**Comment by greazyz** [comment]
Hi Fatima, 
The photo you inserted to introduce this site made it feel like it was a news article. I would like to incorporate this into my future projects. You explained a lot of the steps, report definitions, and insights throughout the report, making it really engaging and easy to follow.

Written Communication: 10
Project Skeleton: 10
Formatting & Display: 10
Code Quality: 10
Extra credit: 2

Score: 52/50
